// ============================================================
// TradeMind AI - Backtest Report Generator
// ============================================================
// Generates comprehensive backtest reports in multiple
// formats: text, JSON, and markdown.
// ============================================================

/**
 * Format a number as percentage
 */
function pct(value, decimals = 2) {
  return (value * 100).toFixed(decimals) + '%';
}

/**
 * Format a number as currency
 */
function usd(value, decimals = 2) {
  return '$' + value.toLocaleString('en-US', {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  });
}

/**
 * Generate text report
 */
function generateTextReport(results) {
  const { summary, performance, trades } = results;
  const lines = [
    '='.repeat(60),
    '         TradeMind AI - Backtest Report',
    '='.repeat(60),
    '',
    '--- Summary ---',
    `Initial Capital:    ${usd(summary.initialCapital)}`,
    `Final Equity:       ${usd(summary.finalEquity)}`,
    `Total Return:       ${pct(summary.totalReturn)}`,
    `Max Drawdown:       ${pct(summary.maxDrawdown)}`,
    `Trading Days:       ${summary.tradingDays}`,
    `Total Trades:       ${summary.totalTrades}`,
    `Win Rate:           ${pct(summary.winRate)}`,
    '',
    '--- Performance ---',
    `Annualized Return:  ${pct(performance.annualizedReturn)}`,
    `Annualized Vol:     ${pct(performance.annualizedVolatility)}`,
    `Sharpe Ratio:       ${performance.sharpeRatio.toFixed(3)}`,
    `Sortino Ratio:      ${performance.sortinoRatio.toFixed(3)}`,
    `Calmar Ratio:       ${performance.calmarRatio.toFixed(3)}`,
    '',
    '--- Trade Statistics ---',
    `Winners:            ${summary.winningTrades}`,
    `Losers:             ${summary.losingTrades}`,
    `Avg Win:            ${usd(trades.avgWin)}`,
    `Avg Loss:           ${usd(trades.avgLoss)}`,
    `Largest Win:        ${usd(trades.largestWin)}`,
    `Largest Loss:       ${usd(trades.largestLoss)}`,
    `Profit Factor:      ${trades.profitFactor.toFixed(3)}`,
    `Avg Holding Period: ${trades.avgHoldingPeriod.toFixed(1)} bars`,
    `Total Commission:   ${usd(trades.totalCommission)}`,
    `Total Slippage:     ${usd(trades.totalSlippage)}`,
    '',
    '='.repeat(60),
  ];
  return lines.join('\n');
}

/**
 * Generate JSON report
 */
function generateJSONReport(results) {
  return JSON.stringify({
    generatedAt: new Date().toISOString(),
    summary: results.summary,
    performance: results.performance,
    tradeStatistics: results.trades,
    monthlyReturns: calculateMonthlyReturns(results.equity),
    drawdownAnalysis: analyzeDrawdowns(results.equity),
    tradeDistribution: analyzeTradeDistribution(results.tradesList),
  }, null, 2);
}

/**
 * Generate Markdown report
 */
function generateMarkdownReport(results) {
  const { summary, performance, trades } = results;
  return `# TradeMind AI - Backtest Report

Generated: ${new Date().toISOString()}

## Summary

| Metric | Value |
|--------|-------|
| Initial Capital | ${usd(summary.initialCapital)} |
| Final Equity | ${usd(summary.finalEquity)} |
| Total Return | ${pct(summary.totalReturn)} |
| Max Drawdown | ${pct(summary.maxDrawdown)} |
| Trading Days | ${summary.tradingDays} |
| Total Trades | ${summary.totalTrades} |
| Win Rate | ${pct(summary.winRate)} |

## Performance Metrics

| Metric | Value |
|--------|-------|
| Annualized Return | ${pct(performance.annualizedReturn)} |
| Annualized Volatility | ${pct(performance.annualizedVolatility)} |
| Sharpe Ratio | ${performance.sharpeRatio.toFixed(3)} |
| Sortino Ratio | ${performance.sortinoRatio.toFixed(3)} |
| Calmar Ratio | ${performance.calmarRatio.toFixed(3)} |

## Trade Statistics

| Metric | Value |
|--------|-------|
| Winners | ${summary.winningTrades} |
| Losers | ${summary.losingTrades} |
| Avg Win | ${usd(trades.avgWin)} |
| Avg Loss | ${usd(trades.avgLoss)} |
| Largest Win | ${usd(trades.largestWin)} |
| Largest Loss | ${usd(trades.largestLoss)} |
| Profit Factor | ${trades.profitFactor.toFixed(3)} |
| Avg Holding Period | ${trades.avgHoldingPeriod.toFixed(1)} bars |
| Total Commission | ${usd(trades.totalCommission)} |

## Monthly Returns

${formatMonthlyTable(results.equity)}

---
*Report generated by TradeMind AI Backtesting Engine*
`;
}

/**
 * Calculate monthly returns from equity curve
 */
function calculateMonthlyReturns(equity) {
  if (!equity || equity.length < 2) return {};

  const months = {};
  for (let i = 1; i < equity.length; i++) {
    const d = new Date(equity[i].timestamp);
    const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
    if (!months[key]) {
      months[key] = { start: equity[i - 1].equity, end: equity[i].equity };
    } else {
      months[key].end = equity[i].equity;
    }
  }

  const result = {};
  for (const [key, val] of Object.entries(months)) {
    result[key] = (val.end - val.start) / val.start;
  }
  return result;
}

/**
 * Analyze drawdown periods
 */
function analyzeDrawdowns(equity) {
  if (!equity || equity.length < 2) return { periods: 0, maxDrawdown: 0, avgDrawdown: 0 };

  const periods = [];
  let peak = equity[0].equity;
  let inDrawdown = false;
  let ddStart = 0;
  let ddDepth = 0;

  for (let i = 0; i < equity.length; i++) {
    if (equity[i].equity >= peak) {
      if (inDrawdown) {
        periods.push({
          start: ddStart,
          end: i - 1,
          depth: ddDepth,
          recovery: i - ddStart,
        });
        inDrawdown = false;
      }
      peak = equity[i].equity;
    } else {
      if (!inDrawdown) {
        ddStart = i;
        inDrawdown = true;
      }
      const dd = (peak - equity[i].equity) / peak;
      if (dd > ddDepth) ddDepth = dd;
    }
  }

  return {
    periods: periods.length,
    maxDrawdown: periods.length > 0 ? Math.max(...periods.map(p => p.depth)) : 0,
    avgDrawdown: periods.length > 0 ? periods.reduce((s, p) => s + p.depth, 0) / periods.length : 0,
    longestDrawdown: periods.length > 0 ? Math.max(...periods.map(p => p.recovery)) : 0,
  };
}

/**
 * Analyze trade distribution
 */
function analyzeTradeDistribution(trades) {
  if (!trades || trades.length === 0) return {};

  const pnls = trades.map(t => t.pnl).sort((a, b) => a - b);
  const mid = Math.floor(pnls.length / 2);

  return {
    count: trades.length,
    median: pnls.length % 2 === 0 ? (pnls[mid - 1] + pnls[mid]) / 2 : pnls[mid],
    std: Math.sqrt(pnls.reduce((s, p) => s + (p - pnls.reduce((a, b) => a + b) / pnls.length) ** 2, 0) / pnls.length),
    percentile25: pnls[Math.floor(pnls.length * 0.25)],
    percentile75: pnls[Math.floor(pnls.length * 0.75)],
  };
}

/**
 * Format monthly returns as markdown table
 */
function formatMonthlyTable(equity) {
  const monthly = calculateMonthlyReturns(equity);
  const years = {};

  for (const [key, val] of Object.entries(monthly)) {
    const [year, month] = key.split('-');
    if (!years[year]) years[year] = {};
    years[year][parseInt(month)] = val;
  }

  let table = '| Year | Jan | Feb | Mar | Apr | May | Jun | Jul | Aug | Sep | Oct | Nov | Dec | Total |\n';
  table += '|------|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-------|\n';

  for (const [year, months] of Object.entries(years).sort()) {
    let total = 0;
    const cells = [];
    for (let m = 1; m <= 12; m++) {
      if (months[m] !== undefined) {
        cells.push(pct(months[m], 1));
        total += months[m];
      } else {
        cells.push('-');
      }
    }
    table += `| ${year} | ${cells.join(' | ')} | ${pct(total, 1)} |\n`;
  }

  return table;
}

/**
 * Main reporter class
 */
class Reporter {
  /**
   * Generate report in specified format
   */
  static generate(results, format = 'text') {
    switch (format.toLowerCase()) {
      case 'text':
        return generateTextReport(results);
      case 'json':
        return generateJSONReport(results);
      case 'markdown':
      case 'md':
        return generateMarkdownReport(results);
      default:
        throw new Error(`Unsupported format: ${format}`);
    }
  }

  /**
   * Save report to file
   */
  static async save(results, filePath, format = 'text') {
    const fs = require('fs').promises;
    const report = Reporter.generate(results, format);
    await fs.writeFile(filePath, report, 'utf-8');
    return filePath;
  }
}

module.exports = { Reporter, generateTextReport, generateJSONReport, generateMarkdownReport };
